import {
  ApplicationsContentApps,
  Description,
  Dots,
  InfoContainer,
  InfoContainerInner,
  Phones,
  Title,
  TreLogo,
} from "@components/components/Home/style";
import MainContainer from "@components/components/MainContainer";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <InfoContainer>
          <InfoContainerInner>
            <TreLogo src="/icons/tre-mobile.svg" alt="tre-mobile" />
            <Title>მატარებლის ბილეთების აპლიკაცია</Title>
            <Description>
              მარტივად მოძებნე და შეიძინე ბილეთები სასურველი მიმართულებით მთელი
              საქართველოს მასშტაბით
            </Description>
            <ApplicationsContentApps>
              <a
                href="https://apps.apple.com/us/app/tre-train-tickets/id6449191931"
                target="_blank"
                rel="noreferrer"
              >
                <img src="/icons/app-store.svg" alt="app store" />
              </a>
              <a
                href="https://play.google.com/store/apps/details?id=com.lemondo.tre"
                target="_blank"
                rel="noreferrer"
              >
                <img src="/icons/play-store.svg" alt="play store" />
              </a>
            </ApplicationsContentApps>
          </InfoContainerInner>
          <Phones src="/icons/phones.svg" alt="phones" />
        </InfoContainer>
      </MainContainer>
    </>
  );
}
